version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./employee-api
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=employeeDB
    depends_on:
      - mongo
    networks:
      - app-network
    
  frontend:
    build: ./employee-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # for SSL certs if used
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    hostname: keycloak
    command: start-dev
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
